# Generated by Django 3.2.4 on 2021-07-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_f1'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSMAR_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleiD', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Sampledesc', models.CharField(blank=True, max_length=500, null=True)),
                ('UserName', models.CharField(blank=True, max_length=30)),
                ('Value_F1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F7', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F8', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F9', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Value_F10', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('QSMAR_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='F1',
        ),
    ]
