# Generated by Django 3.2.4 on 2021-07-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210720_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QSMAR_mst',
            new_name='Qsmart',
        ),
    ]
