# Generated by Django 3.2.4 on 2021-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_qsmar_mst_qsmart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qsmart',
            name='SampleiD',
        ),
        migrations.AddField(
            model_name='qsmart',
            name='Samplename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
