# Generated by Django 3.2.4 on 2021-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210720_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='qsmart',
            name='Qremarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
