# Generated by Django 3.2.4 on 2021-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_qsmart_qremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Range_min', models.IntegerField()),
                ('Range_high', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('StabilityslopeRemark', models.CharField(blank=True, max_length=100, null=True)),
                ('Failures', models.CharField(blank=True, max_length=100, null=True)),
                ('Remborder', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Range_min', models.IntegerField()),
                ('Range_high', models.IntegerField()),
                ('Support_suggested', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
