# Generated by Django 3.2.4 on 2021-07-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remarks_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='Support_suggested',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
