# Generated by Django 3.2.4 on 2021-07-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_suggestion_support_suggested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='Range_high',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='Range_min',
            new_name='min',
        ),
    ]
